field: 5c0f30f6-a3c5-41a9-a362-bb1d11e5a96a
fieldLayouts:
  64219775-3360-46a8-b60d-47811e7eb7a3:
    tabs:
      -
        fields:
          72852746-8cd4-4513-a750-9edc0a8a86fc:
            required: false
            sortOrder: 4
          77e88e3f-cd87-48a3-87b7-72b46083e88f:
            required: false
            sortOrder: 2
          ecd1e29c-668c-4e36-af76-1183b5272a7e:
            required: false
            sortOrder: 1
          ef94451a-fb51-4d76-be6e-8496fa9767b3:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  72852746-8cd4-4513-a750-9edc0a8a86fc:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:62384952-8782-4cb2-b09b-17413aba3239'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      singleUploadLocationSource: 'volume:62384952-8782-4cb2-b09b-17413aba3239'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:62384952-8782-4cb2-b09b-17413aba3239'
      targetSiteId: null
      useSingleFolder: ''
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  77e88e3f-cd87-48a3-87b7-72b46083e88f:
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: ''
    name: Address
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ecd1e29c-668c-4e36-af76-1183b5272a7e:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ef94451a-fb51-4d76-be6e-8496fa9767b3:
    contentColumnType: text
    fieldGroup: null
    handle: contact
    instructions: ''
    name: Contact
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: address
name: Address
sortOrder: 1
