fieldLayouts:
  f90d29e5-8d36-428f-99e0-72aff3a1e50f:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 3c7300e1-d4d1-4aa8-9ad2-c657dc884363
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b5520ae2-8cf9-4ced-af22-170fa52a4431
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5e42d86b-5107-4875-b074-104a3e864454
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Header
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 2c9a135f-7f0a-44d8-b974-3950fd1465e9
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: homepage
hasTitleField: false
name: Homepage
section: 987f7c1a-fbd1-4816-bae5-c981ccf2024b
sortOrder: 1
titleFormat: '{section.name|raw}'
