contentColumnType: string
fieldGroup: fdef0470-69ff-44e4-9c16-10dfb7e4514a
handle: headerLogo
instructions: ''
name: 'Header Logo'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:62384952-8782-4cb2-b09b-17413aba3239'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add a header logo'
  singleUploadLocationSource: 'volume:62384952-8782-4cb2-b09b-17413aba3239'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:62384952-8782-4cb2-b09b-17413aba3239'
  targetSiteId: null
  useSingleFolder: ''
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
