contentColumnType: string
fieldGroup: d6c20ebe-0e7a-49a2-bcfe-2288dc28b60d
handle: resourceImage
instructions: ''
name: 'Resource Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:62384952-8782-4cb2-b09b-17413aba3239'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add a resource image'
  singleUploadLocationSource: 'volume:80967903-f063-48b6-8ab9-5674ba40df73'
  singleUploadLocationSubpath: /images
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
