contentColumnType: text
fieldGroup: d6c20ebe-0e7a-49a2-bcfe-2288dc28b60d
handle: resourceTeaser
instructions: ''
name: 'Resource Teaser'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
