field: 53eef016-ced4-4844-b529-e72e884bd581
fieldLayouts:
  5ea78d48-6bcf-402a-b2ff-7f7fb4245ee0:
    tabs:
      -
        fields:
          2386b537-b023-4390-bc4a-5245ae17fd73:
            required: false
            sortOrder: 2
          b1a65cf5-29d6-49fa-b639-b54795e87191:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  2386b537-b023-4390-bc4a-5245ae17fd73:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b1a65cf5-29d6-49fa-b639-b54795e87191:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
